### ISSUE TITLE
Too many queries issue

### ISSUE THREAD

**Issue by NiktaFeizi** [bhklab/AnnotationGx#12]
This is how I run the query:
`
pubchem_r2 = lapply(paste0("clean", seq(9)) ,function(col){
                         pubchem_query = getPubChemCompound(na.omit(unlist(drugnames_df[,col])), from='name', to='property', 
                                                         properties=c('Title'), batch=FALSE) 
                       })
`

I usually get blacklisted after "clean2".
Each queried vector contains 821 drug names. 

Here is the error I get:
<simpleError: PubChem Server returned Black status! You could be black listed. The returned state message is:
Request Count status: Black (265%), Request Time status: Green (0%), Service status: Green (7%),
Remaining blocking time: 0:0:2.>

**Comment by sisiranair** [comment]
@jjjermiah can you please look into this?

**Comment by jjjermiah** [comment]
@NiktaFeizi can you update the issue with your sessionInfo output and also confirm that you are using the latest version of AnnotationGx from this repository?

**Comment by NiktaFeizi** [comment]
@jjjermiah I updated the package to the latest version. Now it doesn't even get me through what it did before. 
Here is my code for trying one drug name.

getPubChemCompound("Inulin", from='name', to='property', properties=c('Title'), batch=FALSE) 
  |                                                                                                             |   0%

Error in d$value$value : $ operator is invalid for atomic vectors



> sessionInfo
function (package = NULL) 
{
    z <- list()
    z$R.version <- R.Version()
    z$platform <- z$R.version$platform
    if (nzchar(.Platform$r_arch)) 
        z$platform <- paste(z$platform, .Platform$r_arch, sep = "/")
    z$platform <- paste0(z$platform, " (", 8 * .Machine$sizeof.pointer, 
        "-bit)")
    z$locale <- Sys.getlocale()
    z$running <- osVersion
    z$RNGkind <- RNGkind()
    if (is.null(package)) {
        package <- grep("^package:", search(), value = TRUE)
        keep <- vapply(package, function(x) x == "package:base" || 
            !is.null(attr(as.environment(x), "path")), NA)
        package <- .rmpkg(package[keep])
    }
    pkgDesc <- lapply(package, packageDescription, encoding = NA)
    if (length(package) == 0) 
        stop("no valid packages were specified")
    basePkgs <- sapply(pkgDesc, function(x) !is.null(x$Priority) && 
        x$Priority == "base")
    z$basePkgs <- package[basePkgs]
    if (any(!basePkgs)) {
        z$otherPkgs <- pkgDesc[!basePkgs]
        names(z$otherPkgs) <- package[!basePkgs]
    }
    loadedOnly <- loadedNamespaces()
    loadedOnly <- loadedOnly[!(loadedOnly %in% package)]
    if (length(loadedOnly)) {
        names(loadedOnly) <- loadedOnly
        pkgDesc <- c(pkgDesc, lapply(loadedOnly, packageDescription))
        z$loadedOnly <- pkgDesc[loadedOnly]
    }
    z$matprod <- as.character(options("matprod"))
    es <- extSoftVersion()
    z$BLAS <- as.character(es["BLAS"])
    z$LAPACK <- La_library()
    l10n <- l10n_info()
    if (!is.null(l10n["system.codepage"])) 
        z$system.codepage <- as.character(l10n["system.codepage"])
    if (!is.null(l10n["codepage"])) 
        z$codepage <- as.character(l10n["codepage"])
    class(z) <- "sessionInfo"
    z
}
<bytecode: 0x7fb0dc81e8d8>
<environment: namespace:utils>

**Comment by jjjermiah** [comment]
hi Nikta, please send the result of the function call itself:
`sessionInfo()`

The package version for AnnotationGx should be `AnnotationGx_0.0.5.9002`.

Two notes:
1) in your example call, I'm assuming you meant Insulin instead of Inulin? 
if so, running it will produce a result:
`getPubChemCompound("Insulin", from='name', to='property', properties=c('Title'), batch=FALSE)
  |======================================================================| 100%

      name      CID   Title
1: Insulin 70678557 Insulin`

2) Regardless, this does seem to raise an issue though regarding not being able to handle incorrect names. I will debug during the next sprint.
