### ISSUE TITLE
Fetch OncoTree data

### ISSUE THREAD

**Issue by sisiranair** [bhklab/AnnotationGx#3]
Write a function to fetch annotations from OncoTree 
See API - http://oncotree.mskcc.org/#/home?tab=api

**Comment by ChristopherEeles** [comment]
This package may be useful for this: https://www.bioconductor.org/packages/release/bioc/vignettes/ontoProc/inst/doc/ontoProc.html#relationships-asserted-in-the-cell-ontology

It also has a Cellosaurus Ontology. I guess the only question is how often does it get updated.

**Comment by jjjermiah** [comment]
closed by #25
